INSERT INTO DASHBOARD.KRIM_ENTITY_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','U83224001',SYSDATE,null,1);
 
INSERT INTO DASHBOARD.KRIM_ENTITY_NM_T (ACTV_IND,DFLT_IND,ENTITY_ID,ENTITY_NM_ID,FIRST_NM,MIDDLE_NM,LAST_NM,LAST_UPDT_DT,NM_TYP_CD,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','U83224001',DASHBOARD.KRIM_ENTITY_NM_ID_S.NEXTVAL,'Majda','','Hichy',SYSDATE,'PRFR',null,1);
 
INSERT INTO DASHBOARD.KRIM_ENTITY_ENT_TYP_T (ACTV_IND,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','U83224001','PERSON',SYSDATE,null,1);
 
INSERT INTO DASHBOARD.KRIM_ENTITY_EMAIL_T (ACTV_IND,DFLT_IND,EMAIL_ADDR,EMAIL_TYP_CD,ENTITY_EMAIL_ID,ENTITY_ID,ENT_TYP_CD,LAST_UPDT_DT,OBJ_ID,VER_NBR)
  VALUES ('Y','Y','mahichy@bu.edu','WRK',DASHBOARD.KRIM_ENTITY_EMAIL_ID_S.NEXTVAL,'U83224001','PERSON',SYSDATE,null,1);
 
INSERT INTO DASHBOARD.KRIM_ENTITY_AFLTN_T (ENTITY_AFLTN_ID,OBJ_ID,VER_NBR,ENTITY_ID,AFLTN_TYP_CD,CAMPUS_CD,DFLT_IND,ACTV_IND,LAST_UPDT_DT)
  VALUES (null,null,default,'U83224001','0002','21','Y','Y',default);
 
INSERT INTO DASHBOARD.KRIM_ENTITY_EMP_INFO_T (ENTITY_EMP_ID,OBJ_ID,VER_NBR,ENTITY_ID,ENTITY_AFLTN_ID,EMP_STAT_CD,EMP_TYP_CD,BASE_SLRY_AMT,ACTV_IND,LAST_UPDT_DT,PRMRY_DEPT_CD,PRMRY_IND,EMP_REC_ID)
  VALUES (null,null,default,'U83224001',DASHBOARD.KRIM_ENTITY_AFLTN_ID_S.CURRVAL,'3','A',0,'Y',SYSDATE,'1510500000','Y',2);
 
INSERT INTO DASHBOARD.KRIM_PRNCPL_T (ACTV_IND,ENTITY_ID,LAST_UPDT_DT,OBJ_ID,PRNCPL_ID,PRNCPL_NM,PRNCPL_PSWD,VER_NBR)
  VALUES ('Y','U83224001',SYSDATE,null,'U83224001','mahichy',null,1);
